---

# tasks file for ansible-dockerized-wordpress
- hosts: all
  tasks:
  - name: "Clone repo"
    git:
      repo: https://github.com/docker/getting-started.git
      dest: ./getting-started
      version: master

  - name: "Copy docker compose"
    copy:
      src: ./{{ item }}
      dest: /home/ansible/{{ item }}
    loop:
    - docker-compose.yml

  - name: "Deploy apps"
    docker_compose:
      project_src: ./
      files:
      - docker-compose.yml
